### ISSUE TITLE
음성 파일 수집

### ISSUE THREAD

**Issue by bomij33** [YeojinKim03/With-GANADA#1]
음성 녹음 파일 수집 및 정리

**Comment by So-nja** [comment]
/data/voice_data/raw_mp3 경로에 음성 데이터 파일 mp3 형식으로 업로드 하였습니다.
여성 7인, 남성 1인

**Comment by bomij33** [comment]
원본으로 해당 폴더에 올리기. 한 단어 10번씩. 간격을 좀 두고 녹음하기

**Comment by YeojinKim03** [comment]
/data/voice_data/raw_mp3 경로에 음성 데이터 파일 wav 형식으로 업로드 하였습니다.
여성 3인, 남성 1인

**Comment by So-nja** [comment]
/data/voice_data/raw_mp3 경로에 음성 데이터 파일 mp3 형식으로 업로드 하였습니다.
female13-17 5건, male 03-07 5건
[참고] male_04.mp3 사투리 화자입니다.

**Comment by YeojinKim03** [comment]
/data/voice_data/raw_data 경로에 이름 형식 수정하고 wav파일로 변환한 음성 파일들 업로드하였습니다

**Comment by bomij33** [comment]
child 18명, Female 18명, Male 7명 중 chlid 17번 데이터 제외하고 모두 분류하여 1차 분석용 데이터 생성 완료함

**Comment by bomij33** [comment]
ffff

**Comment by bomij33** [comment]
ㄹㄹ

**Comment by bomij33** [comment]
child 18명, Female 18명, Male 7명 중 chlid 17번 데이터 제외하고 모두 분류하여 1차 분석용 데이터 생성 완료함
