### ISSUE TITLE
Notion 프로젝트 관리 페이지 제작 및 추가

### ISSUE THREAD

**Issue by So-nja** [YeojinKim03/With-GANADA#2]
프로젝트 프로세스 진척도를 체크할 수 있는 Notion 페이지 제작하여 링크 추가

**Comment by YeojinKim03** [comment]
https://bitter-waterlily-190.notion.site/4972bf41c09d433692bbfc8a7cc29996

Notion 페이지 제작하였습니다.

프로젝트 타임라인 업데이트 해 놓았습니다.

**Comment by YeojinKim03** [comment]
220813 회의록 업데이트하였습니다

**Comment by bomij33** [comment]
https://www.notion.so/4972bf41c09d433692bbfc8a7cc29996

**Comment by YeojinKim03** [comment]
220814 회의록 업데이트하였습니다

**Comment by bomij33** [comment]
처리 완료

**Comment by bomij33** [comment]
처리 완료

**Comment by So-nja** [comment]
관리페이지 제작 완료하였습니다.
