### ISSUE TITLE
음성 분류 모델 정확도 향상

### ISSUE THREAD

**Issue by bomij33** [YeojinKim03/With-GANADA#7]
- 레이블 개수를 맞추면 val_acc가 0인 문제 발생함
- CNN 모델로 모델 변경하고 레이블 개수 변경 등 성능 향상 필요

**Comment by bomij33** [comment]
- val_acc NaN 문제 해결결 : 레이블 번호를 0부터 시작하는 것으로 val_acc가 NaN인 문제 해결됨
- 성능 향상
   옵티마이저는 Adam, Adadelta, SGD 등을 테스트해보았으나 Adam이 성능이 제일 좋음 (val_acc : 88)
   epoch는 1000으로 늘려서 val_acc 가 좋아지지 않음
   Conv1D의 kernel_size 는 3, 9, 12 등으로 변화를 주었으나 9일 경우가 제일 성능이 좋음

** 성능 향상을 위한 코드 변경은 진전 없음

**Comment by bomij33** [comment]
A 단계의 3개 음성 파일로 모델 생성 시, val_acc : 89%. 
(fit 진행중 출력시에는 val_acc 95%, acc 99% 나왔음. )
모델 저장하여 서버 프로그래밍 시 사용할 수 있도록 드라이브(공유) 에 업로드 함
https://drive.google.com/drive/folders/1OdoiLZ9IjcGsYMJvcfw5tR-oA3DdC5q4?usp=sharing

A, B, C 각 단계마다 레이블 index는 0부터 시작해야 함.
음성 파일 개수나 퀄리티에 따라 성능은 달라질 수 있을 것으로 보이며, 추가적인 성능 향상 필요함

**Comment by YeojinKim03** [comment]
음성 정확도 향상 모두 확인하였고 이슈 종료하겠습니다
